version: '3.4'

networks:
  default:
    external:
      name: nat

services:
  quotesgenerator:
    image: dsanjay/quotesgenerator:multi
    build:
      context: .
      dockerfile: Dockerfile 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80"