version: '3.4'

services:
  quotesgenerator:
    image: dsanjay/quotesgenerator:latest
    build:
      context: .
      dockerfile: Dockerfile 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80"